-- Drop remaining old policies that still allow anonymous access
DROP POLICY IF EXISTS "Authenticated users can manage their own alert preferences" ON public.alert_pref;
DROP POLICY IF EXISTS "Authenticated users can manage assets for their projects" ON public.assets;
DROP POLICY IF EXISTS "Authenticated team members can view project comments" ON public.comment;
DROP POLICY IF EXISTS "Authenticated users can manage their own comments" ON public.comment;
DROP POLICY IF EXISTS "Authenticated users can manage their own construction items" ON public.construction_item;
DROP POLICY IF EXISTS "Authenticated users can manage their own emails" ON public.email_queue;
DROP POLICY IF EXISTS "Authenticated users can view exchange rates" ON public.exchange_rates;
DROP POLICY IF EXISTS "Authenticated users can view benchmarks" ON public.feasly_benchmarks;
DROP POLICY IF EXISTS "Team members can view project comments" ON public.feasly_comments;
DROP POLICY IF EXISTS "Authenticated users can manage their own KPI snapshots" ON public.kpi_snapshot;
DROP POLICY IF EXISTS "Organization admins can view audit logs" ON public.organization_audit_logs;
DROP POLICY IF EXISTS "Authenticated users can view their own invitations" ON public.organization_invitations;
DROP POLICY IF EXISTS "Organization admins can manage invitations" ON public.organization_invitations;
DROP POLICY IF EXISTS "Authenticated admins can manage members" ON public.organization_members;
DROP POLICY IF EXISTS "Authenticated users can view their own membership" ON public.organization_members;
DROP POLICY IF EXISTS "Authenticated users can view their organizations" ON public.organizations;
DROP POLICY IF EXISTS "Organization admins can update organizations" ON public.organizations;
DROP POLICY IF EXISTS "Authenticated users can delete their own profile only" ON public.profiles;
DROP POLICY IF EXISTS "Authenticated users can update their own profile only" ON public.profiles;
DROP POLICY IF EXISTS "Authenticated users can view their own profile only" ON public.profiles;
DROP POLICY IF EXISTS "Authenticated users can insert their own profile only" ON public.profiles;
DROP POLICY IF EXISTS "Team members can delete project contractors" ON public.project_contractors;
DROP POLICY IF EXISTS "Team members can update project contractors" ON public.project_contractors;
DROP POLICY IF EXISTS "Team members can view project contractors" ON public.project_contractors;
DROP POLICY IF EXISTS "Team members can create project contractors" ON public.project_contractors;
DROP POLICY IF EXISTS "Authenticated users can manage their own project drafts" ON public.project_drafts;
DROP POLICY IF EXISTS "Authenticated users can view templates" ON public.project_input_templates;
DROP POLICY IF EXISTS "Users can manage their own templates" ON public.project_input_templates;
DROP POLICY IF EXISTS "Authenticated project owners can manage team" ON public.project_team;
DROP POLICY IF EXISTS "Authenticated organization members can manage org projects" ON public.projects;
DROP POLICY IF EXISTS "Authenticated users can manage their own projects" ON public.projects;
DROP POLICY IF EXISTS "Authenticated users can view their projects" ON public.projects;